# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Make tmux automatically restore after restart
set -g @continuum-restore 'on'

# set autosave interval to 5 minutes
set -g @continuum-save-interval '5'

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Set theme
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "cwd continuum"
set -g @dracula-show-powerline true
set -g @dracula-continuum-colors "dark_gray red"
set -g @dracula-show-left-icon "#[fg=#ba181b] #S"
set -g @dracula-cwd-max-dirs "0"
set -g @dracula-cwd-max-chars "35"
set -g @dracula-show-left-sep "​"
set -g @dracula-show-right-sep "​"
set -g @dracula-show-empty-plugins false

#161a1d - my grey
#ba181b - my red
#f5f3f4 - my white
set -g @dracula-colors "
# Dracula Color Pallette
white='#f5f3f4'
gray='#161a1d'
dark_gray='#161a1d'
light_purple='#ba181b'
dark_purple='#ba181b'
cyan='#ba181b'
green='#161a1d'
orange='#ba181b'
red='#ba181b'
pink='#ba181b'
yellow='#f5f3f4'
"


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
